version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    docker:
      - image: 'cimg/node:12'
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test
          JWT_SECRET: something
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      - image: 'circleci/postgres:9.6.2-alpine'
        environment:
          POSTGRES_USER: psqluser
          POSTGRES_PASSWORD: psqlpassword
          POSTGRES_DB: psdb

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp 
      - run: yarn install  
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - run: yarn test:e2e
      - save_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}      
          paths:
            - ~/.node_modules